version: '3'

services:
  db-dev:
    image: postgres
    volumes:
      - db_data_dev:/var/lib/postgresql/data/

  backend-dev:
    build: ./backend
    command: yarn start:dev
    volumes:
      - ./backend:/app/backend
    ports:
      - "3001:3001"
    depends_on:
      - db-dev

  frontend-dev:
    build: ./frontend
    command: yarn start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"

volumes:
  db_data_dev:

